.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/docs-improvements.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/support.md

For #11: It adds 4 most frequently used templates for issues: bug report, feature request, docs improvements, support. And they almost include all issue types in BH and Hist (*I think it would be nice if we put ToDo issues into [projects](https://github.com/scikit-hep/hist/projects)*).

Add issue templates

---

.github/workflows/cd.yml

Adding deploy CD. ~~Won't work until we get a token from PyPI.~~ Secret added.
Note that when we release a new version, it will need to start with a number larger than 1.0.6, which is the last release on PyPI for "hist".

ci: Adding deploy

---

src/hist/axis.py
src/hist/core.py
src/hist/utils.py
tests/test_bh.py

Last important piece for Uproot demo.
For now, metadata is the raw metadata object, so users can change "title" and "name" there, and non-dict metadata is likely to be a problem. But should be fine for now.

feat: support bh conversion

---

src/hist/basehist.py
src/hist/namedhist.py
tests/test_named.py

There should be a len check on all operations inside the histogram `__init__`, was missing from NamedHist.

fix: Support namedhist shortcut

---

src/hist/axis/__init__.py
tests/test_axis.py

These can still be used as strings, and through `**kwargs`, so better to allow more.
This also removes the ability to change the name, which I think uproot4 uses, so I'll restore before merging.

feat: allow any name

---

src/hist/namedhist.py
src/hist/quick_construct.py
tests/test_base.py
tests/test_general.py
tests/test_named.py

@henryiii Fix the error of "axis name could not be found" in
```python
h = NamedHist.new.Reg(10, 0, 1, name="x").WeightedMean().fill(x=[0.5, 0.5], weight=[1, 1], sample=[1, 1])
```
and allow TestClass to work (update `.new` proxy tests).

fix: fix kwargs in .fill() for WeightedMean&Mean storage

---

README.md
pyproject.toml

The build fails (with a very odd error message, see https://github.com/FFY00/python-build/issues/107) when the build-backend line is missing. It should be there anyway, so adding it.

fix: better build and simpler README

---

src/hist/classichist.py

`os.get_terminal_size` fail when there is no terminal connected (e.g. CI):
```
+ hist --help
Traceback (most recent call last):
File "/home/conda/staged-recipes/build_artifacts/hist_1601700363608/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/hist", line 11, in <module>
sys.exit(main())
File "/home/conda/staged-recipes/build_artifacts/hist_1601700363608/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/hist/classichist.py", line 21, in main
default=os.get_terminal_size()[0], …
```

Use shutil.get_terminal_size instead of os.get_terminal_size

---

docs/changelog.rst
src/hist/plot.py

I was playing with `Hist.plot_pull` and noticed that the range of the pulls is dynamic, meaning it is calculated from `max(np.abs(pulls)) / pp_num` in the code. This is not ideal since (1) pull plots are basically always displayed between -5 and 5, and (2) having several pull plots side-by-side would likely provide ranges on a plot-by-plot case, which is not ideal.
This little PR fixes the issue. It also makes sure that the colour bands by default are set at 1/2/.../5 sigma.
I will post an issue with some other matters related to the function.
Next week I will be giving some lectures and will be showing `Hist`. If at all possible it would be great to have this in a release :-).

Hist.plot_pull: more suitable bands in the pull bands 1sigma, 2 sigma, etc.

---

.github/workflows/ci.yml
.pre-commit-config.yaml
docs/changelog.rst
docs/user-guide/notebooks/SVGHistogram.ipynb
setup.cfg
setup.py
src/hist/basehist.py
src/hist/plot.py
src/hist/svgplots.py

Can this be released as 2.1.0 so that we get a consistent set of packages for the next `scikit-hep` metapackage release, see https://github.com/scikit-hep/scikit-hep/pull/133? Advance thanks.

boost-histogram and histoprint dependencies update

---

src/hist/plot.py
tests/test_plot.py

Closes #157. Still accepting "guas" to allow ROOT style usage.

refactor: allow gauss or gaus (ROOT style)

---

docs/changelog.rst
src/hist/__init__.py
src/hist/axestuple.py
src/hist/axis/__init__.py
src/hist/plot.py
src/hist/tag.py
src/hist/typing.py

I’ve used Python 3.7 module-level `__getattr__`  for a while now to allow mistyping hist.axis import as hist.axes to show a warning but work anyway. However, I completely missed a fantastic usage for Python 3.7 module-level `__dir__ `: you can “fix” IPython’s tab completion to just show the items in `__all__`! Wow! One of the main things that bugged me about importing and defining unrelated things in modules, and one reason that boost-histogram has an `_internal` module. It was almost a parenthetical comment on the classic article here:  https://snarky.ca/lazy-importing-in-python-3-7/

fix: cleaner IPython import completion for Python 3.7+

---

src/hist/basehist.py
tests/test_general.py
tests/test_named.py
tests/test_profile.py

Closes #156, adds a `.profile` method. Based heavily on @aminnj's example.
TODO:
* This probably could be a WeightedMean, probably give a choice? Just got the basics working for now. (Can revisit later)
Followup:
* histoprint should handle showing kind=MEAN histograms (it doesn't like the NaN's, I think) CC @ast0815 (edit: done!)
* mplhep should show a better plot style for kind=MEAN, and should also ensure it handles kind=MEAN's requirements (we could also dispatch differently, but the best fix would be in mplhep) CC @andrzejnovak
* Boost-histogram should describe accumulators/storages a bit more in the docs, especially setting with a stack, including the correct order. CC Me
If kind=MEAN, you are only supposed to plot variances if `counts() > 1`, and values if `counts() >= 1`.

feat: adding profile for COUNT -> MEAN conversion

---

docs/user-guide/notebooks/Plots.ipynb

Resolves #188
This PR revised the Plot notebook in the user's guide to note the return structure of both `plot_ratio` and `plot_pull` is a tuple of matplotlib artists and to expand on the use of both callables and `str` aliases in both APIs.
Relevant section of RTD preview: https://hist--190.org.readthedocs.build/en/190/user-guide/notebooks/Plots.html#Via-Plot-Pull

docs: Revise plot_ratio and plot_pull API examples in user guide

---

setup.py

I think this slipped in from boost-histogram, and is unused. CC https://github.com/readthedocs/recommonmark/issues/221

docs: remove recommonmark

---

src/hist/basehist.py
tests/test_general.py

This might be the only problem causing the segfault, though I thought I saw it in bh::fill. Doing `np.max([])` is undefined.
Fixes #215

fix: empty display (0 size axes) shouldn't try to plot

---

src/hist/axis/__init__.py
tests/test_reprs.py

fix: reprs had missing information

---

src/hist/basehist.py
tests/test_axis.py

fix: modify error message and add warning

---

src/hist/basehist.py
src/hist/quick_construct.py
tests/test_general.py

This address #251 by adding full names too; the mistake I was worried about, a user doing this:
```python
Hist(Hist.new.Regular(10,0,1))
```
is much less likely now that we have the ".new" part (before we didn't), and if someone does make that mistake, mypy will complain - and if they don't type check it, it will just work anyway! :)

feat: support full names and mistaken usage for QuickConstruct

---

src/hist/basehist.py
tests/test_general.py

When completed, closes #222 
To implement:
- sort by passing index
- sort by passing lambda to sorted
- add tests
@henryiii could you take a look? I had to abuse some design decisions of hist to get this work, so maybe you can recommend better workarounds. 
- AxisNamedTuple (and I assume axes) as well cannot be assigned to, so I had to recreate the sorted axis
- Couldn't easily copy all meta/traits from old axis to new - hence the helper with inspect (name/label don't seem to be part of traits/metadata) - also cannot create axis and edit metadata
Here is a couple of examples 
2D - yax
2D - xax
1D
3D - sort on not-projected axis

feat: axis sort

---

noxfile.py
pyproject.toml
setup.py
src/hist/stack.py
tests/test_stacks.py

- tests: nicer config
- fix: support label and better testing

fix: more testing and label support

---

docs/changelog.rst
docs/user-guide/notebooks/Plots.ipynb
src/hist/intervals.py

Resolves #195
Add an `"efficiency"` option to `ratio_uncertainty`'s `uncertainty_type` kwarg that acts as an alias for the `poisson-ratio` option. Additionally add an example of making an efficiency plot to the user guide.

feat: Add "efficiency" option to rp_uncertainty_type kwarg

---

docs/changelog.rst
docs/user-guide/notebooks/Plots.ipynb
src/hist/intervals.py
src/hist/plot.py
tests/test_intervals.py

Fixes #277.
```
* Use the correct Clopper-Pearson interval for an efficiency ratio as for efficiency numerator is subset of denominator
- Update docstring to reflect this
* Add default values for ratio plot ylabel and ylim if `efficiency` option used
* Correct efficiency plot example in user guide
* Add test to ensure no uncertainties are above 1
```

fix: Use proper Clopper-Pearson interval for efficiency ratio

---

noxfile.py

Removes Python 3.6 from `noxfile.py`

chore: update noxfile.py to drop Python 3.6

---

docs/changelog.rst
src/hist/intervals.py
tests/test_intervals.py

- Fix a bug that erroneously sets the upper Clopper-Pearson interval to 0 when the numerator is zero
- Properly scale the poisson-ratio interval bounds
- Ensure poisson interval lower bound is 0 for 0 observed
Closes #279

Fix Clopper-Pearson and poisson ratio intervals

---

.pre-commit-config.yaml
setup.cfg
src/hist/basehist.py
src/hist/intervals.py
src/hist/plot.py
src/hist/svgplots.py

chore: update Numpy and the matching syntax

---

pyproject.toml

Should be building with setuptools_scm 6.3.0

chore: bump setuptools (for setuptools_scm)

---

.pre-commit-config.yaml

As noted in https://github.com/scikit-hep/hist/pull/276#issuecomment-912956178 there is now a `black[jupyter]` extra that allows for Black to run on Jupyter notebooks. `nbqa-black` does this, but Marco Gorelli contributed this functionality to Black so now the `black-jupyter` hook will be the equivalent hook as running `black` and `nbqa-black`.
c.f. https://github.com/scikit-hep/pyhf/pull/1598 for more details / an example
**Suggested squash and merge commit message**
```
* Use jupyter-black pre-commit hook id from Black
- black-jupyter will run on Python and pyi files, so it replaces the black hook id as well
* Remove nbqa-black pre-commit hook from nbQA
- Marco Gorelli essentially contributed nbqa-black to Black in the form of jupyter-black
* Update the pyupgrade version used as an …
```

chore: Use `black-jupyter` pre-commit hook over `nbqa-black`

---

docs/changelog.md

- Fix broken link due to `>` character at the end

docs: fix typo in changelog

---

README.md

- Fix link for PyHEP 2021 talk

docs: fix talk link in readme

---

src/hist/plot.py

The `ax`-argument in `plot_stack` wasn't given to the internally called `histplot` function and then `ax` was overwritten with the axis in the return value of `histplot`. Instead, the argument should be forwarded.

Fix `ax` arg being ignored by `plot_stack()`

---

docs/user-guide/quickstart.rst

Referencing to #35, implementing with `h` instead of `hist`

Changing name of hist variable to h

---

setup.py
src/hist/basehist.py

Closes https://github.com/scikit-hep/hist/issues/337 - a better fix will be in boost-histogram on a longer time scale, and hopefully in Boost.Histogram on a much longer time scale (see https://github.com/boostorg/histogram/issues/353).

fix: temporary patch on broken sum with empty axis

---

src/hist/basehist.py
src/hist/svgplots.py
tests/test_reprs.py

Closes #379 . Also fixes an issue with an empty histogram breaking by not initializing. This adds a hardcoded limit on the SVG size, 1000 for 1D and 200 in either diminsion for 2D (can increase if we move to using a bitmap). Closes #380. We could make this configurable possibly, but a hard limit is just fine at the moment too - you can always plot, this is just a visual helper.

fix: repr limit and fallback on normal repr

---

docs/examples/HistDemo.ipynb
docs/index.rst

- Fix link for `Examples` in `index`
- Remove empty cell in example

docs: fix link and cleanup demo

---

MANIFEST.in
README.md
binder/postBuild

Add Binder support by using the [postBuild configuration file](https://mybinder.readthedocs.io/en/latest/using/config_files.html) to install the required dependencies needed by the user guide notebooks.  Additionally, add a launch Binder badge to the README.
preview on this branch: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/scikit-hep/hist/docs/add-binder-support)

feat: Add Binder support 

---

docs/index.rst
docs/reference/hist.accumulators.rst
docs/reference/hist.axestuple.rst
docs/reference/hist.axis.rst
docs/reference/hist.basehist.rst
docs/reference/hist.classichist.rst
docs/reference/hist.hist.rst
docs/reference/hist.intervals.rst
docs/reference/hist.namedhist.rst
docs/reference/hist.numpy.rst
docs/reference/hist.rst
docs/reference/hist.stack.rst
docs/reference/hist.storage.rst
docs/reference/hist.tag.rst
docs/reference/hist.version.rst
docs/reference/modules.rst

I was going through the documentation of `hist` to get some inspiration for `vector`, and I found some minor problems with the structure of the API docs. Some of the docs are hidden deep under the web pages, and some of them are not listed in the index. Here is what the changes look like -

docs: fix the structure of API docs

---

CITATION.cff
MANIFEST.in

Resolves #413
* Add Citation File Format file to repo to get repository cite button on GitHub and citation support on Zenodo.
- c.f. https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files
For additional context and examples c.f. https://github.com/scikit-hep/pyhf/pull/1551
The schema used is validated by [`cffconvert`](https://pypi.org/project/cffconvert/)
```console
$ pipx install cffconvert
$ cffconvert --validate --infile CITATION.cff 
Citation metadata are valid according to schema version 1.2.0.
```

docs: Add CITATION.cff Citation File Format file

---

.github/dependabot.yml

Remove obsolete configuration from `dependabot.yml`

chore: cleanup dependabot.yml

---

docs/changelog.md
src/hist/axis/__init__.py
src/hist/stack.py

Some of #445.
- fix: nicer stack repr
- fix: avoid listing label when unset

fix: more useful repr for stack

---

.github/workflows/ci.yml
pyproject.toml

I was adding `Pylint` to `vector` and discovered these redundant lines here 😅

chore: remove redundant MANIFEST related metadata

---

.github/workflows/ci.yml
.pre-commit-config.yaml
README.md
docs/banner_slides.md
docs/user-guide/axes.rst
docs/user-guide/numpy.rst
docs/user-guide/quickstart.rst
docs/user-guide/storages.rst
docs/user-guide/subclassing.rst

https://scientific-python.github.io/repo-review/?repo=scikit-hep%2Fhist&branch=main

chore: auto-cancel & blacken-docs

---

.pre-commit-config.yaml
pyproject.toml

See https://github.com/scientific-python/cookie/issues/201.
Committed via https://github.com/asottile/all-repos

chore: target-version no longer needed by Black or Ruff

---

.github/workflows/ci.yml
README.md
docs/changelog.md

Having `fill_flattened` would be nice. Also `integrate`.

chore: prepare for 2.7

---

README.md
pyproject.toml
src/hist/plot.py

Adding `iminuit` breaks WebAssembly until we get it added to Pyodide. Let's split the extras.

fix: plot extra split into [fit]

---

src/hist/basehist.py
tests/test_general.py

feat: add a .T shortcut

---

pyproject.toml
src/hist/basehist.py

Adding some mypy codes and it helped work out this issue.

fix: support ND quick constructs being mistakenly passed in

---

noxfile.py
tests/test_general.py
tests/test_mock_plot.py
tests/test_named.py

It's now easy to test against the latest development version of boost-histogram with `nox -Rs boost`. Used to clean up reset of sloppy integer tests.

fix: support boost-histogram 1.4+ (+ nox)

---

.github/workflows/ci.yml
docs/user-guide/notebooks/Histogram.ipynb
pyproject.toml
src/hist/axis/__init__.py
tests/test_general.py

- feat: adding overflow disable option to cat axes
- ci: add 3.12 testing

feat: add features from boost-histogram 1.4

---

src/hist/basehist.py
tests/test_general.py

Fixes #537.
Also makes the tests pass when using boost-histogram < 1.4.

fix: sample required error message

---

src/hist/dask/__init__.py

This makes it so that `hist.dask` has the equivalent of `hist.new`, which is was missing.

fix: hist.dask.new to match top-level package

---

.github/workflows/cd.yml

* Add generation of GitHub artifact attestations to built sdist and wheel before upload. c.f.:
- https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/
- https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds

ci: Add GitHub artifact attestations to package distribution

---

docs/changelog.md
src/hist/basehist.py

fix: plot1d overlay to work for IntCat axis corrrectly

---

pyproject.toml

```
FAILED tests/test_plot.py::test_general_plot1d - ModuleNotFoundError: No module named 'mplhep'
FAILED tests/test_plot.py::test_general_plot2d - ModuleNotFoundError: No module named 'mplhep'
FAILED tests/test_plot.py::test_general_plot2d_full - ModuleNotFoundError: No module named 'mplhep'
FAILED tests/test_plot.py::test_general_plot - ModuleNotFoundError: No module named 'mplhep'
FAILED tests/test_plot.py::test_general_plot_pull - ModuleNotFoundError: No module named 'mplhep'
FAILED tests/test_plot.py::test_named_plot1d - ModuleNotFoundError: No module named 'mplhep'
FAILED tests/test_plot.py::test_named_plot2d - ModuleNotFoundError: No module named 'mplhep'
FAILED tests/test_plot.py::test_named_plot2d_full - ModuleNotFoundError: No module named 'mplhep'
FAILED …
```

fix: test needs mplhep

---

docs/user-guide/installation.rst
docs/user-guide/notebooks/Transform.ipynb

Hello :) This PR fixes two broken links in the docs that point to [boost-histogram](https://boost-histogram.readthedocs.io/en/latest/)'s docs, one in [`user-guide/notebooks/Transform`](https://hist.readthedocs.io/en/latest/user-guide/notebooks/Transform.html) and the other one in [`user-guide/installation`](https://hist.readthedocs.io/en/latest/user-guide/installation.html).

[DOCS] Fix broken links to boost-histogram docs

---

src/hist/basehist.py
src/hist/namedhist.py

When using`fill_flattened` with multiple args and either the `weight` or `sample` kwargs, it tries to broadcast the keys of `non_user_kwargs` instead of the values, leading to kwargs trying to fill the histogram with the stringified kwarg name instead of its value (such as the `sample` kwarg attempting to fill the array with `["sample", "sample", "sample", "sample"]`). This PR changes that behavior to insert the values instead.

fix: `fill_flattened` broadcasting of non user kwargs

---

.github/workflows/ci.yml

Add pass job, makes it possible to add and remove jobs without failing PRs.

ci: add pass job for tests

---

.pre-commit-config.yaml
pyproject.toml
src/hist/axis/__init__.py
src/hist/basehist.py
src/hist/serialization/__init__.py
tests/test_serialization_uhi.py

Adding serialization. Requires an update of boost-histogram to work correctly, and an update of uhi to be used to write to an output format.

feat: serialization

---

docs/changelog.md

docs: add missing links to changelog
