scikit-hep/hist

setup.cfg
src/hist/axis.py
src/hist/core.py

Adds title if name and title are not set.
@LovelyBuggies take a look, but I'll merge soon, as we need this for @jpivarski's talk. I think it's about the last thing we need in before Monday. I'll make a 2.0 alpha 0 release soon!

feat: update bh, factor out title/name

---

src/hist/axestuple.py
src/hist/core.py
src/hist/named.py
tests/test_general.py

feat: NamedAxesTuple

---

src/hist/basehist.py
tests/test_base.py
tests/test_general.py
tests/test_named.py

feat: add other axes to proxy

---

setup.cfg
src/hist/axestuple.py
src/hist/axis/__init__.py
src/hist/basehist.py

feat: boost-histogram 0.10.0

---

src/hist/basehist.py

feat: plot 1D, 2D return artists

---

.pre-commit-config.yaml
docs/user-guide/notebooks/SVGHistogram.ipynb
src/hist/axis/__init__.py
src/hist/basehist.py
src/hist/classichist.py
src/hist/namedhist.py
src/hist/svgplots.py
src/hist/svgutils.py
tests/test_axis.py
tests/test_base.py
tests/test_general.py
tests/test_named.py

Adding html repr, based on `docs/user-guide/notebooks/SVGHistogram.ipynb`.

feat: add repr

---

setup.cfg
src/hist/axis/__init__.py
tests/test_bh.py

Updating to boost-histogram 0.11, fixes the metadata/title buggy conversion.

feat: new boost-histogram

---

docs/user-guide/notebooks/Axis.ipynb
docs/user-guide/notebooks/Histogram.ipynb
docs/user-guide/notebooks/Plots.ipynb
src/hist/axis/__init__.py
tests/test_axis.py

feat: flow shortcut

---

docs/changelog.rst
src/hist/plot.py

fix: plot2d_full was broken

---

README.md
docs/changelog.rst
src/hist/basehist.py
tests/test_general.py

feat: storage shortcuts

---

src/hist/basehist.py
src/hist/plot.py

fix: support plotting and density for all storages

---

docs/changelog.rst
src/hist/basehist.py
tests/test_general.py

fix: density was not working with special storages

---

README.md
docs/changelog.rst
setup.cfg
src/hist/__init__.py
src/hist/basehist.py
src/hist/plot.py
src/hist/typing.py
tests/test_general.py

feat: from_columns

---

docs/changelog.rst
src/hist/plot.py

Fix for bug reported #146 for the next patch version; will get #148 in for the next minor version.

fix: variances was missing sqrt

---

.github/workflows/ci.yml
.pre-commit-config.yaml
docs/changelog.rst
setup.cfg

chore: bump boost-histogram version

---

src/hist/plot.py

fix(types): better return type

---

docs/changelog.rst
src/hist/plot.py
tests/test_plot.py

Closes #189. Not really pushing one solution over the other yet, but making sure both are available before we drop 3.6 so it will be easier to prefer one over the other eventually.

feat: each axis kw

---

.pre-commit-config.yaml
pyproject.toml
setup.cfg

- chore: bump to mypy 0.901
- chore: move as much as possible to pyproject.toml

chore: bump to MyPy 0.901

---

pyproject.toml

Follow up to #229, much simpler! Clear win now over the setup.cfg version.

style: simpler mypy toml config

---

src/hist/basehist.py

feat: improve axis name error

---

src/hist/axis/__init__.py

fix: adapt docstring for axis name getter

---

README.md

- Change the relative link for CONTRIBUTING.md to the documentation link
- Change bullet point formatting

docs: minor fixes in README.md

---

src/hist/basehist.py
tests/test_mock_plot.py

Fixes #201
- Checks over more traits to ensure correct axes
- Add mock tests to verify the plot being triggered

feat: wrong plottting was triggered

---

setup.cfg
src/hist/basehist.py
tests/test_general.py

- chore: bump boost-histogram
- feat: support list selection from boost-histogram 1.1

feat: boost-histogram 1.1 and selection lists

---

src/hist/basehist.py
tests/test_stacks.py

Found by @LovelyBuggies in #244.

fix: .stack was broken, added test

---

docs/index.rst

docs: add Hist logo and badges to index

---

docs/index.rst
docs/user-guide/analyses.rst

docs: add analyses examples to documentation

---

docs/user-guide/quickstart.rst

Fix #307 (no automatic check added yet, though - might be good idea).

docs: refer to hist, not bh

---

.pre-commit-config.yaml
notebooks/axestuple-setattr.ipynb
setup.cfg
src/hist/axestuple.py
src/hist/plot.py
tests/test_axestuple.py
tests/test_axis.py

feat: bulk name setting for AxesTuple

---

src/hist/stack.py
tests/test_stacks.py

feat: add more methods to Stack

---

src/hist/plot.py

fix: plot should only require scipy/minuit if required

---

src/hist/stack.py
tests/test_stacks.py

Handy constructors. Closes #254.

feat: from_* methods for Stacks

---

docs/changelog.md
src/hist/plot.py

chore: minor cleanup to plot.__all__

---

src/hist/stack.py

fix: avoid runtime dependency on matplotlib

---

.github/workflows/cd.yml
dev-environment.yml
setup.cfg

feat: use boost-histogram 1.3.1

---

docs/user-guide/axes.rst

docs: fix minor typos in Axes

---

setup.py
src/hist/plot.py

fix: only require scipy if used

---

.github/ISSUE_TEMPLATE/docs-improvements.md
.github/ISSUE_TEMPLATE/support.md

Remove auto assigning of @henryiii and @LovelyBuggies in `docs-improvements.md` and `support.md`

chore: remove auto assigning in issues

---

noxfile.py

Change the localhost URL from `http://localhost:8000/` to ` http://localhost:8001/`

chore: modify localhost URL for Nox

---

README.md
docs/index.rst

- Add license badge to `README.md` and rearrange old links
- Update badges in the documentation

docs: add badges and update documentation

---

.git_archival.txt
.gitattributes

This should allow versioning from a git archive (including GitHub's auto-generated one).

fix(setup): support building from an archive

---

.git_archival.txt
.gitignore

See https://github.com/scikit-hep/scikit-hep.github.io/pull/250.

fix(setup): better behavior building from an archive

---

src/hist/basehist.py
src/hist/svgplots.py
tests/test_general.py

Signed-off-by: Henry Schreiner <henryschreineriii@gmail.com>

chore: add storagetype backport

---

.github/workflows/ci.yml
pyproject.toml

Signed-off-by: Henry Schreiner <henryschreineriii@gmail.com>

chore: Python 3.11

---

src/hist/basehist.py
src/hist/namedhist.py
src/hist/plot.py
src/hist/stack.py

A few small things. One message is left, but I think it's a bug in reverb.

chore: minor cleanups from reverb

---

docs/user-guide/accumulators.rst
docs/user-guide/analyses.rst
docs/user-guide/axes.rst
docs/user-guide/numpy.rst
docs/user-guide/quickstart.rst
docs/user-guide/storages.rst
docs/user-guide/subclassing.rst

docs: change code directives to code-block

---

.github/CONTRIBUTING.md

Add command to list all sessions

docs: add nox -l command

---

.github/workflows/ci.yml

chore: add Python 3.11 final for CI

---

.pre-commit-config.yaml
docs/conf.py
pyproject.toml
src/hist/__init__.py
src/hist/basehist.py
src/hist/classichist.py
src/hist/intervals.py
src/hist/namedhist.py
src/hist/plot.py
src/hist/stack.py
tests/conftest.py
tests/test_axis.py
tests/test_dask.py
tests/test_general.py
tests/test_named.py
tests/test_reprs.py

chore: move to using Ruff

---

.readthedocs.yml
docs/conf.py
docs/contributing.md
docs/index.rst
docs/reference/hist.axis.rst
docs/reference/hist.axis.transform.rst
docs/reference/hist.dask.hist.rst
docs/reference/hist.dask.namedhist.rst
docs/reference/hist.dask.rst
docs/reference/hist.plot.rst
docs/reference/hist.quick_construct.rst
docs/reference/hist.rst
docs/reference/hist.svgplots.rst
docs/reference/hist.svgutils.rst
docs/reference/modules.rst
docs/user-guide/cli.rst
docs/user-guide/notebooks/Plots.ipynb
docs/user-guide/notebooks/Transform.ipynb
noxfile.py
pyproject.toml

Simpler, reducing warnings, adding recent additions to API.

docs: rework and rerun API

---

src/hist/basehist.py
tests/test_general.py

feat: Add a function to integrate axes

---

.github/workflows/cd.yml

ci: trusted publisher

---

noxfile.py
pyproject.toml

Bumping and improving pylint config a bit.

chore: bump pylint

---

pyproject.toml
tests/test_stacks.py

Getting ready for the next release.

fix: support boost-histogram 1.4+

---

docs/user-guide/storages.rst

* Use the same information as provided by boost-histogram in https://github.com/scikit-hep/boost-histogram/pull/876

docs: Clarify sample term required for Mean storage

---

.pre-commit-config.yaml
docs/user-guide/notebooks/SVGHistogram.ipynb
pyproject.toml

Modernizing and using Ruff's built-in notebook support.

chore: move to using Ruff Jupyter support

---

.github/dependabot.yml
.github/release.yml
.pre-commit-config.yaml

With merge, GHA is probably better monthly.

ci: reduce frequency

---

.github/workflows/ci.yml
.pre-commit-config.yaml
README.md
docs/user-guide/installation.rst
pyproject.toml
src/hist/_compat/typing.py
src/hist/axis/__init__.py
src/hist/basehist.py
src/hist/interop.py
src/hist/intervals.py
src/hist/plot.py
src/hist/svgutils.py

Python 3.8+, boost-histogram 1.5 allowed.

feat: Python 3.8+, boost-histogram 1.5

---

.github/workflows/ci.yml
noxfile.py
pyproject.toml

See https://github.com/dask-contrib/dask-awkward/pull/566. This needs to be fixed, limiting is temporary!

tests: limit dask

---

.github/workflows/ci.yml
README.md
docs/user-guide/accumulators.rst
pyproject.toml
src/hist/basehist.py
src/hist/interop.py
src/hist/plot.py
src/hist/quick_construct.py
src/hist/stack.py
tests/test_axestuple.py

feat: drop Python 3.8

---

docs/conf.py
noxfile.py

Modernize noxfile and docs job.

chore: modernize noxfile

---

pyproject.toml

chore: SPDX license

---

pyproject.toml

Close #626.
Were there other places?

chore: add some authors

---

pyproject.toml
src/hist/interop.py
tests/test_interop.py

fix: fill flattened pass-through strings

---

docs/conf.py

docs: one more missing author
